### ISSUE TITLE
no checkpoint file

### ISSUE THREAD

**Issue by wangjiangyuan** [stau-7001/S3AI#2]
I used 'python main.py --config=configs/test_on_sarscov2.yml' 

FileNotFoundError: [Errno 2] No such file or directory: '/userhome/lyt/S3AI/runs/MultiTask_S3AI_Chem_IC50_Sarscov2_S3AI_rerun_fix_data_123_28-11_04-24-38/best_checkpoint.pt'

Please check and upload the best chekpoint file.

**Comment by wangjiangyuan** [comment]
oops, I think I found the link.

**Comment by YidongSong** [comment]
Can you open the link? The link seems to be inaccessible.

**Comment by stau-7001** [comment]
> Can you open the link? The link seems to be inaccessible.

If you are in China, you may need a global proxy VPN to access Figshare.
